### ISSUE TITLE
AC - customJWT lambda

### ISSUE THREAD

**Issue by IvanDLar** [IvanDLar/MOVU-BackEnd#58]
## Description

Create a lambda function that will create update a user and add custom claims to it. The lambda will recieve the firebase user id in the request body. (since the account was previously created on google before). 

![Image](https://user-images.githubusercontent.com/57450093/231618455-aa2e473c-6dbc-44d4-9ad6-f220c9881fb2.png)

in our case. `setCustomClaims({role: "customer})`

## Acceptance Criteria

* Create jwt with custom claims 
* Return jwt with said claims

**Comment by sofferjacob** [comment]
Ticket not implemented, customers will not have custom claims
